name: Deploy Next.js site to Pages

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Pages は同時実行を 1 つに制限（途中のデプロイはキャンセルしない）
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build (Next.js export)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # GitHub Pages 向けの Next.js 自動設定（basePath/画像最適化の無効化など）
      # 自前で next.config を完全管理したい場合は削除可
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next
          generator_config_file: next.config.ts

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"

      # Next.js のビルドキャッシュを再利用
      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Next.js ビルド → 静的エクスポート
      # ※ next.config.* に { output: 'export' } を設定しておくこと
      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: |
          pnpm build
          npx next export --out ./out

      # out/ を Pages へアップロード
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
